import './global.css';
import './icons';

// TODO change
export const metadata = {
  title: 'Welcome to vsezol',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen">{children}</body>
    </html>
  );
}
